/**
 * Complete geographic data for Cuba: 16 provinces and 168 municipalities.
 */

export interface GeoOption {
  value: string;
  label: string;
}

export const CUBA_PROVINCES: GeoOption[] = [
  { value: 'pinar_del_rio', label: 'Pinar del Río' },
  { value: 'artemisa', label: 'Artemisa' },
  { value: 'la_habana', label: 'La Habana' },
  { value: 'mayabeque', label: 'Mayabeque' },
  { value: 'matanzas', label: 'Matanzas' },
  { value: 'villa_clara', label: 'Villa Clara' },
  { value: 'cienfuegos', label: 'Cienfuegos' },
  { value: 'sancti_spiritus', label: 'Sancti Spíritus' },
  { value: 'ciego_de_avila', label: 'Ciego de Ávila' },
  { value: 'camaguey', label: 'Camagüey' },
  { value: 'las_tunas', label: 'Las Tunas' },
  { value: 'holguin', label: 'Holguín' },
  { value: 'granma', label: 'Granma' },
  { value: 'santiago_de_cuba', label: 'Santiago de Cuba' },
  { value: 'guantanamo', label: 'Guantánamo' },
  { value: 'isla_de_la_juventud', label: 'Isla de la Juventud' },
];

export const CUBA_MUNICIPALITIES: Record<string, GeoOption[]> = {
  pinar_del_rio: [
    { value: 'sandino', label: 'Sandino' },
    { value: 'mantua', label: 'Mantua' },
    { value: 'minas_de_matahambre', label: 'Minas de Matahambre' },
    { value: 'vinales', label: 'Viñales' },
    { value: 'la_palma', label: 'La Palma' },
    { value: 'los_palacios', label: 'Los Palacios' },
    { value: 'consolacion_del_sur', label: 'Consolación del Sur' },
    { value: 'pinar_del_rio', label: 'Pinar del Río' },
    { value: 'san_luis', label: 'San Luis' },
    { value: 'san_juan_y_martinez', label: 'San Juan y Martínez' },
    { value: 'guane', label: 'Guane' },
  ],
  artemisa: [
    { value: 'bahia_honda', label: 'Bahía Honda' },
    { value: 'mariel', label: 'Mariel' },
    { value: 'guanajay', label: 'Guanajay' },
    { value: 'caimito', label: 'Caimito' },
    { value: 'bauta', label: 'Bauta' },
    { value: 'san_antonio_de_los_banos', label: 'San Antonio de los Baños' },
    { value: 'guira_de_melena', label: 'Güira de Melena' },
    { value: 'alquizar', label: 'Alquízar' },
    { value: 'artemisa', label: 'Artemisa' },
    { value: 'candelaria', label: 'Candelaria' },
    { value: 'san_cristobal', label: 'San Cristóbal' },
  ],
  la_habana: [
    { value: 'playa', label: 'Playa' },
    { value: 'plaza_de_la_revolucion', label: 'Plaza de la Revolución' },
    { value: 'centro_habana', label: 'Centro Habana' },
    { value: 'habana_vieja', label: 'Habana Vieja' },
    { value: 'regla', label: 'Regla' },
    { value: 'habana_del_este', label: 'Habana del Este' },
    { value: 'guanabacoa', label: 'Guanabacoa' },
    { value: 'san_miguel_del_padron', label: 'San Miguel del Padrón' },
    { value: 'diez_de_octubre', label: 'Diez de Octubre' },
    { value: 'cerro', label: 'Cerro' },
    { value: 'marianao', label: 'Marianao' },
    { value: 'la_lisa', label: 'La Lisa' },
    { value: 'boyeros', label: 'Boyeros' },
    { value: 'arroyo_naranjo', label: 'Arroyo Naranjo' },
    { value: 'cotorro', label: 'Cotorro' },
  ],
  mayabeque: [
    { value: 'bejucal', label: 'Bejucal' },
    { value: 'san_jose_de_las_lajas', label: 'San José de las Lajas' },
    { value: 'jaruco', label: 'Jaruco' },
    { value: 'santa_cruz_del_norte', label: 'Santa Cruz del Norte' },
    { value: 'madruga', label: 'Madruga' },
    { value: 'nueva_paz', label: 'Nueva Paz' },
    { value: 'san_nicolas', label: 'San Nicolás' },
    { value: 'guines', label: 'Güines' },
    { value: 'melena_del_sur', label: 'Melena del Sur' },
    { value: 'batabano', label: 'Batabanó' },
    { value: 'quivican', label: 'Quivicán' },
  ],
  matanzas: [
    { value: 'matanzas', label: 'Matanzas' },
    { value: 'cardenas', label: 'Cárdenas' },
    { value: 'marti', label: 'Martí' },
    { value: 'colon', label: 'Colón' },
    { value: 'perico', label: 'Perico' },
    { value: 'jovellanos', label: 'Jovellanos' },
    { value: 'pedro_betancourt', label: 'Pedro Betancourt' },
    { value: 'limonar', label: 'Limonar' },
    { value: 'union_de_reyes', label: 'Unión de Reyes' },
    { value: 'cienaga_de_zapata', label: 'Ciénaga de Zapata' },
    { value: 'jaguey_grande', label: 'Jagüey Grande' },
    { value: 'calimete', label: 'Calimete' },
    { value: 'los_arabos', label: 'Los Arabos' },
  ],
  villa_clara: [
    { value: 'corralillo', label: 'Corralillo' },
    { value: 'quemado_de_guines', label: 'Quemado de Güines' },
    { value: 'sagua_la_grande', label: 'Sagua la Grande' },
    { value: 'encrucijada', label: 'Encrucijada' },
    { value: 'camajuani', label: 'Camajuaní' },
    { value: 'caibarien', label: 'Caibarién' },
    { value: 'remedios', label: 'Remedios' },
    { value: 'placetas', label: 'Placetas' },
    { value: 'santa_clara', label: 'Santa Clara' },
    { value: 'cifuentes', label: 'Cifuentes' },
    { value: 'santo_domingo', label: 'Santo Domingo' },
    { value: 'ranchuelo', label: 'Ranchuelo' },
    { value: 'manicaragua', label: 'Manicaragua' },
  ],
  cienfuegos: [
    { value: 'aguada_de_pasajeros', label: 'Aguada de Pasajeros' },
    { value: 'rodas', label: 'Rodas' },
    { value: 'palmira', label: 'Palmira' },
    { value: 'lajas', label: 'Lajas' },
    { value: 'cruces', label: 'Cruces' },
    { value: 'cumanayagua', label: 'Cumanayagua' },
    { value: 'cienfuegos', label: 'Cienfuegos' },
    { value: 'abreus', label: 'Abreus' },
  ],
  sancti_spiritus: [
    { value: 'yaguajay', label: 'Yaguajay' },
    { value: 'jatibonico', label: 'Jatibonico' },
    { value: 'taguasco', label: 'Taguasco' },
    { value: 'cabaiguan', label: 'Cabaiguán' },
    { value: 'fomento', label: 'Fomento' },
    { value: 'trinidad', label: 'Trinidad' },
    { value: 'sancti_spiritus', label: 'Sancti Spíritus' },
    { value: 'la_sierpe', label: 'La Sierpe' },
  ],
  ciego_de_avila: [
    { value: 'chambas', label: 'Chambas' },
    { value: 'moron', label: 'Morón' },
    { value: 'bolivia', label: 'Bolivia' },
    { value: 'primero_de_enero', label: 'Primero de Enero' },
    { value: 'ciro_redondo', label: 'Ciro Redondo' },
    { value: 'florencia', label: 'Florencia' },
    { value: 'majagua', label: 'Majagua' },
    { value: 'ciego_de_avila', label: 'Ciego de Ávila' },
    { value: 'venezuela', label: 'Venezuela' },
    { value: 'baragua', label: 'Baraguá' },
  ],
  camaguey: [
    { value: 'carlos_manuel_de_cespedes', label: 'Carlos Manuel de Céspedes' },
    { value: 'esmeralda', label: 'Esmeralda' },
    { value: 'sierra_de_cubitas', label: 'Sierra de Cubitas' },
    { value: 'minas', label: 'Minas' },
    { value: 'nuevitas', label: 'Nuevitas' },
    { value: 'guaimaro', label: 'Guáimaro' },
    { value: 'sibanicu', label: 'Sibanicú' },
    { value: 'camaguey', label: 'Camagüey' },
    { value: 'florida', label: 'Florida' },
    { value: 'vertientes', label: 'Vertientes' },
    { value: 'jimaguayu', label: 'Jimaguayú' },
    { value: 'najasa', label: 'Najasa' },
    { value: 'santa_cruz_del_sur', label: 'Santa Cruz del Sur' },
  ],
  las_tunas: [
    { value: 'manati', label: 'Manatí' },
    { value: 'puerto_padre', label: 'Puerto Padre' },
    { value: 'jesus_menendez', label: 'Jesús Menéndez' },
    { value: 'majibacoa', label: 'Majibacoa' },
    { value: 'las_tunas', label: 'Las Tunas' },
    { value: 'jobabo', label: 'Jobabo' },
    { value: 'colombia', label: 'Colombia' },
    { value: 'amancio', label: 'Amancio' },
  ],
  holguin: [
    { value: 'gibara', label: 'Gibara' },
    { value: 'rafael_freyre', label: 'Rafael Freyre' },
    { value: 'banes', label: 'Banes' },
    { value: 'antilla', label: 'Antilla' },
    { value: 'baguanos', label: 'Báguanos' },
    { value: 'holguin', label: 'Holguín' },
    { value: 'calixto_garcia', label: 'Calixto García' },
    { value: 'cacocum', label: 'Cacocum' },
    { value: 'urbano_noris', label: 'Urbano Noris' },
    { value: 'cueto', label: 'Cueto' },
    { value: 'mayari', label: 'Mayarí' },
    { value: 'frank_pais', label: 'Frank País' },
    { value: 'sagua_de_tanamo', label: 'Sagua de Tánamo' },
    { value: 'moa', label: 'Moa' },
  ],
  granma: [
    { value: 'rio_cauto', label: 'Río Cauto' },
    { value: 'cauto_cristo', label: 'Cauto Cristo' },
    { value: 'jiguani', label: 'Jiguaní' },
    { value: 'bayamo', label: 'Bayamo' },
    { value: 'yara', label: 'Yara' },
    { value: 'manzanillo', label: 'Manzanillo' },
    { value: 'campechuela', label: 'Campechuela' },
    { value: 'media_luna', label: 'Media Luna' },
    { value: 'niquero', label: 'Niquero' },
    { value: 'pilon', label: 'Pilón' },
    { value: 'bartolome_maso', label: 'Bartolomé Masó' },
    { value: 'buey_arriba', label: 'Buey Arriba' },
    { value: 'guisa', label: 'Guisa' },
  ],
  santiago_de_cuba: [
    { value: 'contramaestre', label: 'Contramaestre' },
    { value: 'mella', label: 'Mella' },
    { value: 'san_luis', label: 'San Luis' },
    { value: 'segundo_frente', label: 'Segundo Frente' },
    { value: 'songo_la_maya', label: 'Songo-La Maya' },
    { value: 'santiago_de_cuba', label: 'Santiago de Cuba' },
    { value: 'palma_soriano', label: 'Palma Soriano' },
    { value: 'tercer_frente', label: 'Tercer Frente' },
    { value: 'guama', label: 'Guamá' },
  ],
  guantanamo: [
    { value: 'el_salvador', label: 'El Salvador' },
    { value: 'manuel_tames', label: 'Manuel Tames' },
    { value: 'yateras', label: 'Yateras' },
    { value: 'baracoa', label: 'Baracoa' },
    { value: 'maisi', label: 'Maisí' },
    { value: 'imias', label: 'Imías' },
    { value: 'san_antonio_del_sur', label: 'San Antonio del Sur' },
    { value: 'caimanera', label: 'Caimanera' },
    { value: 'guantanamo', label: 'Guantánamo' },
    { value: 'niceto_perez', label: 'Niceto Pérez' },
  ],
  isla_de_la_juventud: [
    { value: 'isla_de_la_juventud', label: 'Isla de la Juventud' },
  ],
};
