// ============================================================
// TriciGo — Delivery Service
// Handles delivery/messaging-specific operations.
// ============================================================

import { getSupabaseClient } from '../client';
import type { PackageCategory, VehicleType } from '@tricigo/types';

export interface DeliveryDetails {
  id: string;
  ride_id: string;
  package_description: string;
  recipient_name: string;
  recipient_phone: string;
  estimated_weight_kg: number | null;
  special_instructions: string | null;
  package_category: PackageCategory | null;
  package_length_cm: number | null;
  package_width_cm: number | null;
  package_height_cm: number | null;
  client_accompanies: boolean;
  delivery_vehicle_type: VehicleType | null;
  pickup_photo_url: string | null;
  delivery_photo_url: string | null;
  /** 4-digit OTP autogenerated by the `generate_delivery_otp` trigger.
      Shared with the recipient by the rider; required by the driver at
      drop-off to unlock the +5% cargo bonus. */
  delivery_otp: string | null;
  delivery_otp_validated_at: string | null;
  created_at: string;
}

export interface CreateDeliveryParams {
  ride_id: string;
  package_description: string;
  recipient_name: string;
  recipient_phone: string;
  estimated_weight_kg?: number;
  special_instructions?: string;
  package_category?: PackageCategory;
  package_length_cm?: number;
  package_width_cm?: number;
  package_height_cm?: number;
  client_accompanies?: boolean;
  delivery_vehicle_type?: VehicleType;
}

/**
 * Public view of a delivery (anonymous recipient via share_token).
 * Mirrors the RPC `get_public_delivery_by_token`. Privacy-safe fields only.
 */
export interface PublicDeliveryView {
  ride_id: string;
  status: string;
  pickup_lat: number;
  pickup_lng: number;
  pickup_address: string | null;
  dropoff_lat: number;
  dropoff_lng: number;
  dropoff_address: string | null;
  accepted_at: string | null;
  pickup_at: string | null;
  arrived_at_destination_at: string | null;
  completed_at: string | null;
  canceled_at: string | null;
  estimated_duration_s: number;
  customer_first_name: string | null;
  recipient_first_name: string | null;
  driver_first_name: string | null;
  driver_avatar_url: string | null;
  driver_rating: number | null;
  vehicle_make: string | null;
  vehicle_model: string | null;
  vehicle_color: string | null;
  vehicle_plate: string | null;
  vehicle_type: string | null;
  package_description: string | null;
  package_category: string | null;
  pickup_photo_url: string | null;
  delivery_photo_url: string | null;
}

/** Result of validate_delivery_otp RPC. */
export interface ValidateOtpResult {
  success: boolean;
  /** `too_many_attempts` comes from check_rate_limit inside the RPC: 5 tries per
      600s per ride (00427). It was missing from this union, so the UI had no
      branch for it and showed a generic failure while the driver stood locked
      out at the customer's door. */
  error?: 'forbidden' | 'no_otp_set' | 'invalid_otp' | 'too_many_attempts' | string;
}

/** Rate-limit window enforced by validate_delivery_otp (check_rate_limit, 00427):
    5 attempts per 600 seconds, keyed per ride. Mirrored here so the UI can tell
    the driver how long the wait is instead of just saying "error". */
export const DELIVERY_OTP_LOCKOUT_SECONDS = 600;

export const deliveryService = {
  /**
   * Create delivery details for a ride.
   */
  async createDeliveryDetails(params: CreateDeliveryParams): Promise<DeliveryDetails> {
    const supabase = getSupabaseClient();

    const { data, error } = await supabase
      .from('delivery_details')
      .insert({
        ride_id: params.ride_id,
        package_description: params.package_description,
        recipient_name: params.recipient_name,
        recipient_phone: params.recipient_phone,
        estimated_weight_kg: params.estimated_weight_kg ?? null,
        special_instructions: params.special_instructions ?? null,
        package_category: params.package_category ?? null,
        package_length_cm: params.package_length_cm ?? null,
        package_width_cm: params.package_width_cm ?? null,
        package_height_cm: params.package_height_cm ?? null,
        client_accompanies: params.client_accompanies ?? false,
        delivery_vehicle_type: params.delivery_vehicle_type ?? null,
      })
      .select()
      .single();

    if (error) throw new Error(error.message);
    return data as DeliveryDetails;
  },

  /**
   * Get delivery details for a ride.
   */
  async getDeliveryDetails(rideId: string): Promise<DeliveryDetails | null> {
    const supabase = getSupabaseClient();

    const { data, error } = await supabase
      .from('delivery_details')
      .select('*')
      .eq('ride_id', rideId)
      .maybeSingle();

    if (error) throw new Error(error.message);
    return data as DeliveryDetails | null;
  },

  /**
   * Update delivery photo URL (called by driver at completion).
   */
  async updateDeliveryPhoto(rideId: string, photoUrl: string): Promise<void> {
    const supabase = getSupabaseClient();

    const { error } = await supabase
      .from('delivery_details')
      .update({ delivery_photo_url: photoUrl })
      .eq('ride_id', rideId);

    if (error) throw new Error(error.message);
  },

  /**
   * Update pickup photo URL (called by driver at package pickup).
   */
  async updatePickupPhoto(rideId: string, photoUrl: string): Promise<void> {
    const supabase = getSupabaseClient();

    const { error } = await supabase
      .from('delivery_details')
      .update({ pickup_photo_url: photoUrl })
      .eq('ride_id', rideId);

    if (error) throw new Error(error.message);
  },

  /**
   * Validate the 4-digit OTP that the recipient hands to the driver at drop-off.
   * Marks delivery_details.delivery_otp_validated_at, which unlocks the +5%
   * cargo bonus trigger.
   *
   * Tolerates the RPC being absent (legacy DB without the OTP feature):
   * returns { success: false, error: 'no_otp_set' } so the UI can show a
   * graceful fallback instead of crashing.
   */
  async validateDeliveryOtp(rideId: string, otp: string): Promise<ValidateOtpResult> {
    const supabase = getSupabaseClient();
    const { data, error } = await supabase.rpc('validate_delivery_otp', {
      p_ride_id: rideId,
      p_otp: otp,
    });
    if (error) {
      // 42883 = undefined_function — RPC not present in this DB
      if (error.code === '42883' || /function.*does not exist/i.test(error.message)) {
        return { success: false, error: 'no_otp_set' };
      }
      throw new Error(error.message);
    }
    return (data ?? { success: false, error: 'no_otp_set' }) as ValidateOtpResult;
  },

  /**
   * Public delivery view via share_token — for the recipient who clicks
   * the SMS link without being authenticated. Uses the SECURITY DEFINER
   * RPC `get_public_delivery_by_token`, which enforces ride_mode='cargo'
   * and share_token_expires_at inline.
   *
   * Returns null when the ride is not cargo (or the token is invalid),
   * so callers can use this in parallel with `getPublicRideByShareToken`
   * and only render the package card when this resolves with data.
   */
  async getPublicDeliveryByToken(token: string): Promise<PublicDeliveryView | null> {
    const supabase = getSupabaseClient();
    const { data, error } = await supabase.rpc('get_public_delivery_by_token', {
      p_token: token,
    });
    if (error) {
      if (error.code === '42883' || /function.*does not exist/i.test(error.message)) {
        return null;
      }
      throw new Error(error.message);
    }
    const row = Array.isArray(data) ? data[0] : data;
    return (row ?? null) as PublicDeliveryView | null;
  },

  /**
   * Upload a delivery photo to Supabase Storage.
   * @param phase 'pickup' or 'delivery' — determines which column is updated
   */
  async uploadDeliveryPhoto(rideId: string, localUri: string, phase: 'pickup' | 'delivery' = 'delivery'): Promise<string> {
    const supabase = getSupabaseClient();

    // Upload via the `upload-delivery-photo` Edge Function (service-role)
    // instead of a direct client → Storage upload: the Storage service rejects
    // the mobile session's user JWT (treats it as anon), so the
    // authenticated-only delivery_photos RLS policy fails ("new row violates
    // row-level security policy") even though PostgREST + gotrue validate the
    // same token. The EF authenticates via gotrue, verifies the caller is the
    // ride's driver, uploads with the service-role key, and records the URL on
    // delivery_details. The photo is sent as multipart FormData (RN-safe file
    // descriptor — fetch(uri).blob() throws on native file:// / content:// URIs).
    const fileName = `${phase}-${rideId}-${Date.now()}.jpg`;
    const formData = new FormData();
    formData.append('file', {
      uri: localUri,
      name: fileName,
      type: 'image/jpeg',
    } as unknown as Blob);
    formData.append('ride_id', rideId);
    formData.append('phase', phase);

    const { data, error } = await supabase.functions.invoke('upload-delivery-photo', {
      body: formData,
    });
    if (error) throw error;
    if (data?.error) throw new Error(String(data.error));

    return (data?.publicUrl ?? '') as string;
  },
};
