-- ============================================================
-- 00384_delivery_recipient_sms_otp.sql
--
-- Add the 4-digit delivery OTP to the SMS the recipient gets when a cargo
-- ride is accepted. Until now that SMS carried only the tracking link
-- (/delivery/<share_token>); the recipient had no way to know the code the
-- driver asks for at drop-off, so they depended on the sender to relay it
-- out-of-band. The OTP already exists at 'accepted' (generated by
-- trg_delivery_details_generate_otp when the delivery row is created), so we
-- just SELECT it and append it to the body.
--
-- This also brings notify_delivery_recipient_on_accept into git: it was an
-- ORPHAN object created directly in prod (not present in any prior
-- migration). The body below is reproduced VERBATIM from prod via
-- pg_get_functiondef, with only three OTP-related additions:
--   1. declare v_otp TEXT
--   2. SELECT dd.delivery_otp INTO v_otp
--   3. append " Codigo para recibir: <otp>" to v_body
--
-- SMS body stays accent-free on purpose ("Codigo", not "Código"): the
-- existing copy avoids non-GSM-7 characters so the message fits in a single
-- SMS segment. Keep new text accent-free too.
--
-- Idempotent: CREATE OR REPLACE. The trigger (trg_notify_delivery_recipient
-- on rides) is unchanged, so no trigger DDL is needed.
-- ============================================================

CREATE OR REPLACE FUNCTION public.notify_delivery_recipient_on_accept()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_catalog'
AS $function$
DECLARE
  v_service_key TEXT;
  v_headers JSONB;
  v_body TEXT;
  v_share_token TEXT;
  v_recipient_phone TEXT;
  v_recipient_first TEXT;
  v_customer_first TEXT;
  v_eta_s INTEGER;
  v_eta_label TEXT;
  v_claimed_rows INTEGER;
  v_otp TEXT;
BEGIN
  IF NEW.ride_mode <> 'cargo' OR NEW.status <> 'accepted' OR OLD.status = 'accepted' THEN
    RETURN NEW;
  END IF;

  UPDATE rides
  SET delivery_recipient_notified_at = NOW()
  WHERE id = NEW.id
    AND delivery_recipient_notified_at IS NULL
  RETURNING share_token, estimated_duration_s
  INTO v_share_token, v_eta_s;

  GET DIAGNOSTICS v_claimed_rows = ROW_COUNT;
  IF v_claimed_rows = 0 OR v_share_token IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT dd.recipient_phone,
         split_part(COALESCE(dd.recipient_name, ''), ' ', 1),
         split_part(COALESCE(u.full_name, ''), ' ', 1),
         dd.delivery_otp
  INTO v_recipient_phone, v_recipient_first, v_customer_first, v_otp
  FROM delivery_details dd
  LEFT JOIN users u ON u.id = NEW.customer_id
  WHERE dd.ride_id = NEW.id
  LIMIT 1;

  IF v_recipient_phone IS NULL OR v_recipient_phone = '' THEN
    RETURN NEW;
  END IF;

  v_service_key := get_service_role_key();
  IF v_service_key IS NULL OR v_service_key = '' THEN
    RAISE WARNING '[notify_recipient] service_role_key missing — skipping send-sms for ride %', NEW.id;
    RETURN NEW;
  END IF;

  v_eta_label := CASE
    WHEN v_eta_s IS NOT NULL AND v_eta_s > 0 THEN '~' || CEIL(v_eta_s / 60.0)::text || ' min'
    ELSE NULL
  END;

  v_body := COALESCE(NULLIF(v_recipient_first, ''), 'Hola') || ', ' ||
            COALESCE(NULLIF(v_customer_first, ''), 'un contacto') ||
            ' te envia un paquete via TriciGo.' ||
            CASE WHEN v_eta_label IS NOT NULL THEN ' ETA ' || v_eta_label || '.' ELSE '' END ||
            ' Sigue tu envio: https://tricigo.com/delivery/' || v_share_token ||
            CASE WHEN v_otp IS NOT NULL AND v_otp <> '' THEN ' Codigo para recibir: ' || v_otp ELSE '' END;

  v_headers := jsonb_build_object(
    'Content-Type', 'application/json',
    'Authorization', 'Bearer ' || v_service_key,
    'apikey', v_service_key
  );

  PERFORM net.http_post(
    url := 'https://lqaufszburqvlslpcuac.supabase.co/functions/v1/send-sms',
    headers := v_headers,
    body := jsonb_build_object(
      'phone', v_recipient_phone,
      'body', v_body,
      'ride_id', NEW.id::text,
      'event_type', 'delivery_recipient_notify'
    )
  );

  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  RAISE WARNING '[notify_recipient] exception for ride %: % %', NEW.id, SQLSTATE, SQLERRM;
  RETURN NEW;
END;
$function$;
