// Unique, reviewed SEO copy per Cuban province. Keyed by province value
// (CUBA_PROVINCES key in @tricigo/utils). Generated from a write -> verify ->
// dedup-critic -> rewrite agent workflow, then committed as static data.
// Each block is genuinely specific to its province (its own municipalities,
// geography); Spanish, neutral Cuban tone, no fabricated statistics.

import type { ProvinceContent } from './coverage';

export const PROVINCE_CONTENT: Record<string, ProvinceContent> = {
  pinar_del_rio: {
    metaDescription: "Pide tu transporte en Pinar del Río con TriciGo: triciclo, moto, auto o mensajería bajo demanda. Precio claro antes de confirmar y viaje seguido en tiempo real.",
    intro: "TriciGo acerca el transporte bajo demanda a Pinar del Río, la provincia más occidental de Cuba. Desde la ciudad cabecera hasta Viñales y los municipios del campo tabacalero, pides tu viaje desde la app y conoces el precio antes de confirmar.",
    bodyParagraphs: [
      "En Pinar del Río, TriciGo conecta a los pasajeros con triciclos, motos y autos, además del servicio de mensajería, todo desde una sola app. En la ciudad cabecera, capital provincial, el triciclo encaja bien para trayectos cortos por sus calles, mientras la moto y el auto sirven para distancias mayores hacia municipios como Consolación del Sur o San Luis. Antes de confirmar ves el precio estimado en CUP, sigues el viaje en tiempo real y eliges pagar en efectivo o con créditos TriciCoin. La cobertura crece por zonas: consulta en la app la disponibilidad actual en tu localidad.",
      "La provincia combina el llano agrícola del sur con los mogotes del valle de Viñales, escenario tabacalero reconocido y muy transitado. TriciGo ayuda a moverse entre puntos de Viñales, La Palma, Minas de Matahambre y los poblados de San Juan y Martínez, donde el transporte puede ser irregular. Pedir un triciclo, una moto o un auto desde el teléfono reduce la espera y da claridad sobre la tarifa. Para llevar paquetes o encargos, la mensajería resuelve envíos dentro de la ciudad o entre municipios cercanos, con seguimiento del trayecto.",
      "Hacia el occidente extremo, municipios como Guane, Mantua y Sandino quedan más alejados de los grandes ejes, por lo que un servicio bajo demanda aporta opciones reales de movilidad. Los Palacios, hacia el este de la provincia, también se beneficia de poder solicitar un viaje sin depender solo del transporte de paso. Con TriciGo eliges el tipo de vehículo según tu necesidad, cuentas con botón SOS y conductores verificados. A medida que TriciGo llega a más zonas de Pinar del Río, más vecinos podrán pedir su triciclo, moto o auto directamente desde la app.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo en Pinar del Río?", a: "Abre la app de TriciGo, indica tu punto de recogida y destino dentro de Pinar del Río, y elige triciclo como tipo de vehículo. Verás el precio estimado antes de confirmar y podrás seguir el viaje en tiempo real. La disponibilidad depende de tu zona: consúltala en la app." },
      { q: "¿En qué municipios de Pinar del Río está TriciGo?", a: "TriciGo se despliega por zonas e incluye localidades como Pinar del Río, Viñales, Consolación del Sur, San Luis, San Juan y Martínez, La Palma, Los Palacios, Minas de Matahambre, Guane, Mantua y Sandino. La cobertura crece progresivamente; revisa en la app la disponibilidad actual en tu municipio." },
      { q: "¿Cuánto cuesta un viaje en Pinar del Río?", a: "El precio depende del tipo de vehículo (triciclo, moto o auto), la distancia y el tiempo del trayecto. Con TriciGo ves el estimado en CUP antes de confirmar, sin sorpresas. Puedes pagar en efectivo o con créditos TriciCoin desde la propia app." },
    ],
  },
  artemisa: {
    metaDescription: "Pide triciclo, moto, auto o mensajería en Artemisa con TriciGo. Transporte bajo demanda con precio claro y conductores verificados. Consulta la disponibilidad.",
    intro: "TriciGo acerca el transporte bajo demanda a la provincia de Artemisa: pide un triciclo, una moto, un auto o un servicio de mensajería desde tu teléfono, con el precio estimado antes de confirmar el viaje.",
    bodyParagraphs: [
      "En Artemisa, una provincia que combina el llano agrícola del sur con la franja costera del norte, TriciGo ofrece una opción para cada trayecto. El triciclo resuelve los recorridos cortos dentro de la cabecera provincial y de pueblos como Güira de Melena o Alquízar; la moto agiliza los viajes rápidos entre barrios; el auto conviene para distancias más largas o cuando viajas con equipaje. La mensajería suma para enviar o recibir paquetes sin moverte. Todo se pide desde la app, con el estimado a la vista antes de aceptar.",
      "La geografía de Artemisa favorece el transporte bajo demanda: municipios agrícolas como San Antonio de los Baños, Bauta y Caimito conviven con Mariel y Bahía Honda en la costa norte, además de Guanajay, Candelaria y San Cristóbal hacia el interior. Las distancias entre estos núcleos hacen útil elegir el vehículo según el viaje. Con TriciGo ves al conductor en el mapa, sigues el recorrido en tiempo real y cuentas con botón SOS y conductores verificados para mayor tranquilidad en cada trayecto.",
      "Pagar es sencillo: puedes hacerlo en efectivo (CUP) o con créditos TriciCoin dentro de la app. El servicio se despliega por zonas, así que la cobertura crece a medida que TriciGo llega a más municipios de Artemisa. Si estás en la cabecera o en localidades como Mariel, Bauta o San Antonio de los Baños, abre la aplicación para consultar qué opciones están activas cerca de ti. Antes de confirmar siempre verás el estimado del viaje, sin sorpresas al llegar a tu destino.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo en Artemisa?", a: "Abre la app de TriciGo, indica tu punto de recogida y tu destino dentro de Artemisa, y elige triciclo como tipo de vehículo. Verás el precio estimado antes de confirmar; al aceptar, podrás seguir al conductor en el mapa en tiempo real hasta que llegue." },
      { q: "¿En qué municipios de Artemisa está disponible TriciGo?", a: "TriciGo se despliega por zonas dentro de la provincia, que incluye municipios como Artemisa, Mariel, Bauta, San Antonio de los Baños, Güira de Melena, Guanajay y San Cristóbal, entre otros. La cobertura crece a medida que llega a tu zona; consulta la disponibilidad real abriendo la app en tu ubicación." },
      { q: "¿Cómo se paga un viaje en Artemisa y en qué moneda?", a: "Puedes pagar en efectivo en pesos cubanos (CUP) o con créditos TriciCoin desde la app. El precio estimado se muestra antes de confirmar el viaje, para que sepas cuánto pagarás sin sorpresas al llegar." },
    ],
  },
  la_habana: {
    metaDescription: "Pide triciclo, moto, auto o mensajería en La Habana con TriciGo. Precio claro antes de confirmar, seguimiento en vivo y conductores verificados. Paga en CUP.",
    intro: "TriciGo conecta a quienes se mueven por La Habana con conductores verificados de triciclo, moto y auto. Pide tu viaje desde la app, conoce el precio antes de confirmar y sigue tu recorrido en tiempo real.",
    bodyParagraphs: [
      "En la capital cubana, TriciGo ofrece triciclo, moto, auto y mensajería para resolver el día a día. El triciclo se mueve con agilidad por las calles estrechas de Habana Vieja, Centro Habana y el Cerro, donde el tránsito suele ser denso. Para trayectos más largos hacia Playa, Plaza de la Revolución o Boyeros, la moto o el auto acortan tiempos. Pides desde la app, ves el estimado antes de confirmar y eliges pagar en efectivo o con créditos TriciCoin, según lo que prefieras en cada viaje.",
      "La movilidad habanera combina barrios muy distintos: el casco histórico de Habana Vieja y Regla junto a la bahía, las zonas residenciales de Playa y Marianao, y municipios más extensos como Arroyo Naranjo, San Miguel del Padrón o Diez de Octubre. El transporte bajo demanda encaja bien aquí porque cada zona pide un vehículo diferente. Con TriciGo eliges el servicio según la distancia y el bolsillo, sigues el viaje en el mapa y cuentas con botón SOS y conductores verificados para mayor tranquilidad.",
      "Más allá del centro, TriciGo busca cubrir municipios como Guanabacoa, Habana del Este, La Lisa y Cotorro, donde llegar a tiempo a un trabajo, una cita o la terminal de ómnibus a veces se complica. El servicio de mensajería permite enviar paquetes y documentos sin moverte, mientras un conductor los traslada por ti. A medida que TriciGo llega a tu zona, podrás coordinar recogidas en distintos puntos de la provincia. Consulta la disponibilidad en la app para ver qué vehículos operan cerca de ti.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo en La Habana?", a: "Abre la app de TriciGo, escribe tu punto de recogida y tu destino dentro de La Habana, y elige el triciclo como tipo de vehículo. Verás el precio estimado antes de confirmar. Una vez aceptado, sigues al conductor en el mapa en tiempo real hasta que llega por ti." },
      { q: "¿En qué municipios de La Habana está disponible TriciGo?", a: "TriciGo se despliega por zonas en la provincia, con presencia en municipios como Habana Vieja, Centro Habana, Plaza de la Revolución, Playa, Diez de Octubre y otros. La cobertura crece a medida que TriciGo llega a más áreas. Consulta la disponibilidad en la app según tu ubicación." },
      { q: "¿Cuánto cuesta un viaje en La Habana?", a: "El precio depende de la distancia, el tipo de vehículo (triciclo, moto o auto) y la zona. Siempre ves el estimado en CUP antes de confirmar, sin sorpresas. Puedes pagar en efectivo o con créditos TriciCoin desde la misma app." },
    ],
  },
  mayabeque: {
    metaDescription: "Pide transporte en Mayabeque con TriciGo: triciclo, moto, auto o mensajería en San José de las Lajas, Güines, Batabanó y más. Precio claro antes de confirmar.",
    intro: "TriciGo conecta a Mayabeque con transporte bajo demanda: desde San José de las Lajas, la cabecera provincial, hasta los pueblos agrícolas del valle y la costa sur. Pides, ves el precio y sigues tu viaje en tiempo real.",
    bodyParagraphs: [
      "En Mayabeque, TriciGo te permite pedir un triciclo para trayectos cortos dentro de San José de las Lajas o Güines, una moto cuando necesitas rapidez entre barrios, o un auto para recorridos más largos entre municipios como Jaruco, Madruga o Nueva Paz. También ofrecemos mensajería para enviar paquetes y documentos. Antes de confirmar ves el precio estimado, eliges pagar en efectivo o con créditos TriciCoin, y sigues el recorrido en el mapa. A medida que TriciGo llega a tu zona, podrás consultar la disponibilidad directamente en la app.",
      "Mayabeque es una provincia mayormente llana y agrícola, al sureste de La Habana, donde el triciclo y la moto cumplen un papel central en la movilidad diaria. En el valle de Güines, Melena del Sur y San Nicolás el movimiento de personas y mercancías es constante, mientras que San José de las Lajas concentra la actividad administrativa como cabecera. El transporte bajo demanda encaja bien aquí: conecta el centro urbano con los repartos y poblados cercanos sin depender de horarios fijos, con conductores verificados y un botón SOS para mayor tranquilidad.",
      "Hacia el sur, Batabanó y su zona costera funcionan como punto de enlace con el golfo y el embarcadero hacia la Isla de la Juventud, mientras Quivicán y Bejucal articulan el tránsito en el oeste provincial y Santa Cruz del Norte mira a la costa norte. TriciGo suma una opción flexible para estos desplazamientos: pedir un viaje desde el teléfono, conocer la tarifa por adelantado y elegir el vehículo según la distancia. Consulta en la app qué servicios ya están activos en tu municipio dentro de Mayabeque.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo o un auto en Mayabeque?", a: "Descarga la app de TriciGo, indica tu punto de recogida y tu destino dentro de Mayabeque, y elige entre triciclo, moto, auto o mensajería. Verás el precio estimado antes de confirmar y podrás seguir el viaje en tiempo real con conductores verificados." },
      { q: "¿En qué municipios de Mayabeque está disponible TriciGo?", a: "TriciGo se despliega por zonas dentro de la provincia, incluyendo áreas como San José de las Lajas, Güines, Batabanó, Bejucal y Quivicán. La cobertura crece a medida que TriciGo llega a tu zona; consulta la disponibilidad actual directamente en la app." },
      { q: "¿Cuánto cuesta un viaje en Mayabeque y cómo se paga?", a: "El precio se calcula según la distancia y el tipo de vehículo, y siempre lo ves estimado en CUP antes de confirmar el viaje. Puedes pagar en efectivo o con créditos TriciCoin desde la propia app, sin sorpresas al finalizar." },
    ],
  },
  matanzas: {
    metaDescription: "Pide transporte en Matanzas con TriciGo: triciclo, moto, auto o mensajería. Viajes con precio claro y seguimiento en tiempo real a medida que llegamos a tu zona.",
    intro: "TriciGo conecta a Matanzas con viajes a pedido en triciclo, moto, auto y mensajería. Desde la ciudad de Matanzas hasta Cárdenas, Jovellanos o Colón, pides desde la app y ves el precio antes de confirmar.",
    bodyParagraphs: [
      "En la provincia de Matanzas, TriciGo te permite moverte a pedido en triciclo, moto o auto, además de enviar paquetes con su servicio de mensajería. La ciudad de Matanzas, cabecera provincial conocida por sus puentes sobre los ríos San Juan y Yumurí, es ideal para trayectos cortos en triciclo entre barrios, mientras que la moto y el auto resuelven distancias mayores. Pides desde la app, ves el precio estimado antes de confirmar y sigues tu viaje en tiempo real, con botón SOS y conductores verificados para mayor tranquilidad.",
      "Matanzas combina ciudades de buen tamaño como Cárdenas y Colón con municipios agrícolas del interior como Perico, Jovellanos, Pedro Betancourt, Calimete y Los Arabos. En estos entornos llanos, donde el transporte público suele ser irregular, el viaje bajo demanda encaja bien: un triciclo para cruzar el pueblo, una moto para llegar rápido o un auto para trasladarte entre Unión de Reyes, Limonar o Martí. Con TriciGo eliges el vehículo según tu necesidad y pagas en efectivo o con créditos TriciCoin.",
      "El servicio de mensajería de TriciGo también ayuda en una provincia extensa que llega hasta la Ciénaga de Zapata y Jagüey Grande, en el sur. Puedes enviar documentos o paquetes pequeños dentro de tu municipio sin desplazarte tú mismo. A medida que TriciGo llega a más zonas de Matanzas, la cobertura se amplía por ciudades y municipios; conviene consultar la disponibilidad directamente en la app, que te muestra los conductores cercanos y el tiempo estimado de llegada antes de pedir.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo o un viaje en Matanzas?", a: "Descarga la app de TriciGo, indica tu punto de recogida y tu destino dentro de Matanzas, y elige el tipo de servicio: triciclo, moto, auto o mensajería. Verás el precio estimado antes de confirmar y, una vez aceptado, podrás seguir al conductor en tiempo real." },
      { q: "¿En qué municipios de Matanzas está disponible TriciGo?", a: "TriciGo se despliega por zonas, comenzando por las áreas de mayor demanda como la ciudad de Matanzas, Cárdenas, Colón y Jovellanos. La cobertura crece a medida que TriciGo llega a tu zona, así que lo más fiable es abrir la app y consultar la disponibilidad de conductores en tu municipio." },
      { q: "¿Cuánto cuesta un viaje en Matanzas y cómo se paga?", a: "El precio depende de la distancia, el tipo de vehículo y la ruta dentro de la provincia. Siempre ves el estimado en CUP antes de confirmar, sin sorpresas. Puedes pagar en efectivo al conductor o con créditos TriciCoin desde tu billetera en la app." },
    ],
  },
  villa_clara: {
    metaDescription: "Pide triciclo, moto, auto o mensajería en Villa Clara con TriciGo. Transporte bajo demanda en Santa Clara, Sagua la Grande, Remedios y más. Paga en CUP.",
    intro: "TriciGo acerca el transporte bajo demanda a Villa Clara, provincia del centro de Cuba con cabecera en Santa Clara. Pide tu viaje desde la app y muévete por la ciudad o entre municipios con tarifa clara antes de confirmar.",
    bodyParagraphs: [
      "En Villa Clara, TriciGo te permite pedir triciclo, moto o auto según tu trayecto, además de mensajería para enviar y recibir paquetes. En Santa Clara, la cabecera provincial y nudo de carreteras del centro del país, el triciclo y la moto resuelven los desplazamientos cortos entre el centro, el Parque Vidal y los repartos; el auto sirve para viajes más largos o con equipaje. Eliges el servicio, ves el precio estimado en CUP antes de confirmar y sigues el viaje en tiempo real con conductores verificados.",
      "La provincia combina llano interior con costa norte, y eso marca cómo se mueve la gente. Sagua la Grande y Caibarién, hacia el litoral, junto a la villa histórica de Remedios, tienen calles donde el triciclo y la moto encajan de forma natural. Placetas, Camajuaní, Ranchuelo, Encrucijada y Manicaragua, este último hacia las estribaciones del Escambray, también suman demanda de transporte cotidiano. Con TriciGo pides según la distancia: un trayecto urbano breve o un viaje entre puntos de un mismo municipio, siempre con la tarifa visible de antemano.",
      "El transporte bajo demanda encaja en Villa Clara porque la actividad se reparte entre la cabecera y municipios como Quemado de Güines, Corralillo, Cifuentes y Santo Domingo, sin un único centro que lo absorba todo. Pedir desde la app evita esperas inciertas: ves quién te recoge, el precio y la ruta. Pagas en efectivo o con créditos TriciCoin, y cuentas con botón SOS para tu tranquilidad. La cobertura se amplía por zonas, así que conviene consultar la disponibilidad en la app a medida que TriciGo llega a tu municipio.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo en Villa Clara?", a: "Abre la app de TriciGo, indica tu punto de recogida y destino dentro de Villa Clara, por ejemplo en Santa Clara, Sagua la Grande o Remedios, y elige triciclo como tipo de servicio. Verás el precio estimado en CUP antes de confirmar y podrás seguir al conductor en tiempo real." },
      { q: "¿Cuánto cuesta un viaje en Villa Clara?", a: "El precio depende de la distancia, el tiempo y el servicio que elijas (triciclo, moto o auto). TriciGo te muestra siempre el estimado en CUP antes de que confirmes, sin sorpresas. Puedes pagar en efectivo o con créditos TriciCoin desde la app." },
      { q: "¿En qué municipios de Villa Clara está TriciGo?", a: "TriciGo se despliega por zonas y va ampliando su cobertura en la provincia, desde Santa Clara hacia municipios como Placetas, Caibarién, Camajuaní, Manicaragua o Santo Domingo. La mejor forma de saber si ya hay servicio en tu zona es consultar la disponibilidad directamente en la app." },
    ],
  },
  cienfuegos: {
    metaDescription: "Pide triciclo, moto, auto o mensajería en Cienfuegos con TriciGo. Transporte bajo demanda con precio claro y conductores verificados. Consulta tu zona.",
    intro: "TriciGo conecta a quienes viven y se mueven en Cienfuegos con triciclos, motos, autos y mensajería a pedido. Desde la ciudad de Cienfuegos hasta Cumanayagua o Aguada de Pasajeros, pide tu viaje desde la app y conoce el precio antes de confirmar.",
    bodyParagraphs: [
      "En Cienfuegos, la provincia del centro-sur cubano asomada a su amplia bahía sobre el mar Caribe, TriciGo ofrece triciclo, moto y auto según la distancia y lo que necesites cargar. El triciclo es ideal para trayectos cortos dentro de la ciudad cabecera y su malecón; la moto resuelve recorridos rápidos por Palmira o Cruces; y el auto cubre viajes más largos hacia Cumanayagua o Abreus. Pides desde la app, ves el estimado antes de confirmar y sigues el viaje en tiempo real. Pagas en efectivo o con créditos TriciCoin.",
      "La movilidad de esta provincia combina la trama urbana de la ciudad de Cienfuegos con municipios agrícolas como Aguada de Pasajeros, Rodas, Lajas y Abreus, donde el cañaveral y los caminos rurales marcan los desplazamientos diarios. El transporte bajo demanda encaja bien aquí: en vez de esperar, pides el vehículo que conviene a cada trayecto. Para llevar paquetes, documentos o compras entre barrios o municipios, la mensajería de TriciGo despacha el envío con el conductor más cercano y seguimiento desde tu teléfono.",
      "TriciGo se despliega por zonas, así que la cobertura crece a medida que llega a tu municipio. Mientras tanto, puedes consultar la disponibilidad en la app para la ciudad de Cienfuegos y localidades como Palmira, Cruces o Cumanayagua. Todos los conductores pasan un proceso de verificación y cada viaje incluye botón SOS para tu tranquilidad. Con precios en CUP mostrados por adelantado y rutas seguidas en tiempo real, pedir un triciclo, una moto o un auto en Cienfuegos es claro y sin sorpresas, tanto para un trámite en el centro como para un viaje entre municipios.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo en Cienfuegos?", a: "Abre la app de TriciGo, escribe tu punto de recogida y destino dentro de Cienfuegos, elige triciclo como tipo de vehículo y confirma. Verás el precio estimado en CUP antes de aceptar y podrás seguir al conductor en tiempo real hasta que llegue." },
      { q: "¿En qué municipios de Cienfuegos está TriciGo?", a: "TriciGo se despliega por zonas, comenzando por la ciudad de Cienfuegos y extendiéndose gradualmente hacia municipios como Palmira, Cruces, Cumanayagua, Lajas, Rodas, Abreus y Aguada de Pasajeros. La mejor forma de saber si ya hay conductores cerca de ti es consultar la disponibilidad directamente en la app." },
      { q: "¿Cuánto cuesta un viaje en Cienfuegos?", a: "El precio depende de la distancia, el tiempo y el tipo de vehículo que elijas (triciclo, moto o auto). TriciGo te muestra el estimado en CUP antes de que confirmes, sin sorpresas. Puedes pagar en efectivo o con créditos TriciCoin desde la app." },
    ],
  },
  sancti_spiritus: {
    metaDescription: "Pide triciclo, moto, auto o mensajería con TriciGo en Sancti Spíritus. Transporte bajo demanda en Trinidad, Cabaiguán, Yaguajay y más. Precio claro y viaje en vivo.",
    intro: "TriciGo acerca el transporte bajo demanda al centro de Cuba: desde la ciudad de Sancti Spíritus, junto al río Yayabo, hasta Trinidad, Cabaiguán y Yaguajay, pides tu viaje desde el celular y ves el precio antes de confirmar.",
    bodyParagraphs: [
      "En la provincia de Sancti Spíritus, TriciGo te permite moverte con triciclo para trayectos cortos por el casco histórico de la cabecera, moto cuando necesitas rapidez, o auto para viajes más largos o con equipaje. Desde el centro espirituano, a orillas del Yayabo, hasta los recorridos hacia Cabaiguán y Fomento, abres la app, marcas tu destino y ves el estimado en CUP antes de confirmar. También cuentas con mensajería para enviar paquetes o documentos dentro de la ciudad o entre municipios cercanos, sin tener que coordinar por tu cuenta cada traslado.",
      "Sancti Spíritus combina ciudades patrimoniales como Trinidad, llanos agrícolas hacia La Sierpe y municipios con fuerte tradición azucarera como Jatibonico, por lo que las necesidades de transporte cambian según el lugar. El triciclo encaja bien en calles estrechas y empedradas, la moto resuelve los trayectos cortos con agilidad y la solicitud de auto resulta útil para conectar Yaguajay o Trinidad con la cabecera. Con TriciGo eliges el vehículo según el trayecto, sigues el viaje en tiempo real y sabes quién te recoge, en una provincia donde el transporte privado ya es parte de la movilidad diaria.",
      "Pagar es flexible: usas efectivo en CUP o créditos TriciCoin desde la propia app, y cada viaje incluye botón SOS y conductores verificados para que viajes con tranquilidad por Sancti Spíritus, Cabaiguán o Fomento. TriciGo se despliega por zonas, así que la cobertura crece a medida que llega a cada municipio; antes de pedir, consulta en la app la disponibilidad real en tu localidad. La idea es simple: que pedir un triciclo, una moto o un auto en el centro de Cuba sea tan directo como tocar un botón, con el precio a la vista desde el inicio.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo en Sancti Spíritus?", a: "Abre la app de TriciGo, escribe tu punto de recogida y tu destino dentro de Sancti Spíritus, elige triciclo y confirma. Verás el precio estimado en CUP antes de aceptar y podrás seguir al conductor en tiempo real hasta que llegue." },
      { q: "¿En qué municipios de Sancti Spíritus está TriciGo?", a: "TriciGo se despliega por zonas dentro de la provincia, que incluye Sancti Spíritus, Trinidad, Cabaiguán, Yaguajay, Jatibonico, Taguasco, Fomento y La Sierpe. La cobertura crece a medida que llega a cada localidad, así que lo más seguro es consultar la disponibilidad actual en la app." },
      { q: "¿Cómo se paga un viaje en Sancti Spíritus?", a: "Puedes pagar en efectivo en pesos cubanos (CUP) o con créditos TriciCoin dentro de la app. El precio estimado aparece antes de confirmar, sin sorpresas, y cada viaje cuenta con botón SOS y conductores verificados." },
    ],
  },
  ciego_de_avila: {
    metaDescription: "Pide triciclo, moto, auto o mensajería en Ciego de Ávila con TriciGo. Transporte bajo demanda en Morón, Chambas y más, con precio claro y pago en CUP.",
    intro: "TriciGo conecta a quienes viven y trabajan en Ciego de Ávila con triciclos, motos y autos a pedido. Desde la cabecera provincial hasta Morón, pides tu viaje en minutos y ves el precio antes de confirmar.",
    bodyParagraphs: [
      "En la provincia de Ciego de Ávila, TriciGo te permite pedir un triciclo para trayectos cortos por la cabecera, una moto para moverte rápido entre calles, o un auto cuando viajas con equipaje o en grupo. También ofrece mensajería para enviar paquetes y documentos. La llanura avileña y las distancias entre el centro y municipios como Morón, Chambas o Primero de Enero hacen del transporte bajo demanda una forma cómoda de resolver el día a día sin depender de la espera en la calle.",
      "Ciego de Ávila es una provincia mayormente llana, de suelos agrícolas y caña, donde el triciclo es parte natural del paisaje urbano. Con TriciGo eliges el vehículo según tu necesidad: triciclo para ir al mercado o a una cita cercana, moto para ganar tiempo, auto para trayectos más largos hacia Morón, Majagua o Ciro Redondo. Antes de confirmar ves el estimado en CUP, sigues el viaje en tiempo real y cuentas con botón SOS y conductores verificados para mayor tranquilidad.",
      "El servicio se despliega por zonas, así que la disponibilidad crece a medida que TriciGo llega a más puntos de la provincia, desde la ciudad de Ciego de Ávila hacia municipios como Florencia, Bolivia, Venezuela y Baraguá. Puedes pagar en efectivo o con créditos TriciCoin, y solicitar tu viaje sin llamadas ni regateos. Consulta en la app qué vehículos están activos cerca de ti; si hay conductores disponibles en tu zona, pedir un triciclo, una moto o un auto toma apenas unos toques.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo en Ciego de Ávila?", a: "Abre la app de TriciGo, escribe tu punto de recogida y destino dentro de Ciego de Ávila, elige triciclo como tipo de vehículo y confirma. Verás el precio estimado en CUP antes de aceptar y podrás seguir el viaje en tiempo real. Si hay conductores disponibles en tu zona, la solicitud se asigna en minutos." },
      { q: "¿En qué municipios de Ciego de Ávila está TriciGo?", a: "TriciGo se despliega por zonas dentro de la provincia, comenzando por la ciudad de Ciego de Ávila y extendiéndose hacia municipios como Morón, Chambas, Majagua o Primero de Enero. La cobertura crece a medida que llegan más conductores. Lo más confiable es abrir la app y consultar la disponibilidad real cerca de tu ubicación." },
      { q: "¿Cuánto cuesta un viaje en Ciego de Ávila?", a: "El precio depende de la distancia, el tipo de vehículo (triciclo, moto o auto) y la ruta dentro de la provincia. Con TriciGo siempre ves el estimado en CUP antes de confirmar, sin sorpresas ni regateos. Puedes pagar en efectivo o con créditos TriciCoin desde la misma app." },
    ],
  },
  camaguey: {
    metaDescription: "Pide transporte en Camagüey con TriciGo: triciclo, moto, auto o mensajería bajo demanda. Precio claro antes de confirmar y seguimiento del viaje en la app.",
    intro: "TriciGo conecta a Camagüey, la provincia más extensa de Cuba, con transporte bajo demanda: pide un triciclo, una moto, un auto o un servicio de mensajería desde tu teléfono y conoce el precio antes de confirmar.",
    bodyParagraphs: [
      "En la ciudad de Camagüey, cabecera provincial conocida por su laberinto de calles y plazas coloniales, el triciclo es parte natural de la movilidad cotidiana. Con TriciGo lo pides desde la app para moverte por el casco histórico, llegar a una cita o cargar las compras, y eliges entre triciclo, moto o auto según tu trayecto. Ves el estimado en CUP antes de confirmar, sigues el viaje en tiempo real y pagas en efectivo o con créditos TriciCoin. A medida que TriciGo llega a más zonas de la ciudad, pedir transporte se vuelve tan simple como abrir el teléfono.",
      "Camagüey es una provincia llana y muy extensa, con municipios distantes entre sí como Florida, Vertientes, Guáimaro, Sibanicú y Santa Cruz del Sur, este último asomado a la costa sur del Caribe. Para esos desplazamientos más largos, el auto y la moto resultan prácticos, mientras el triciclo cubre los recorridos cortos dentro de cada localidad. TriciGo se adapta a esa diversidad: eliges el vehículo que mejor encaja con la distancia y el motivo de tu viaje, sin regateos, con tarifa transparente y conductores verificados.",
      "La mensajería de TriciGo suma una opción útil para la vida diaria y los pequeños negocios de la provincia. Puedes enviar un paquete, documentos o un encargo entre puntos de la ciudad de Camagüey o coordinar entregas hacia municipios como Minas, Nuevitas, Jimaguayú o Esmeralda a medida que el servicio se despliega. Todo desde la misma app: solicitas, ves el costo estimado, sigues el recorrido y cuentas con botón SOS para tu tranquilidad. La disponibilidad varía por zona, así que conviene consultarla directamente en la aplicación.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo en Camagüey?", a: "Abre la app de TriciGo, marca tu punto de recogida y tu destino dentro de Camagüey, elige triciclo (o moto, auto o mensajería) y confirma. Verás el precio estimado en CUP antes de aceptar y podrás seguir al conductor en tiempo real hasta que llegue." },
      { q: "¿En qué municipios de Camagüey está disponible TriciGo?", a: "TriciGo se despliega por zonas, comenzando por la ciudad de Camagüey y ampliándose de forma progresiva hacia municipios como Florida, Vertientes, Nuevitas, Guáimaro o Santa Cruz del Sur. La mejor forma de saber si ya cubre tu zona es consultar la disponibilidad directamente en la app." },
      { q: "¿Cuánto cuesta un viaje en Camagüey y cómo se paga?", a: "El precio depende de la distancia, el tipo de vehículo y el recorrido. La app te muestra un estimado en CUP antes de confirmar, sin sorpresas ni regateos. Puedes pagar en efectivo o con créditos TriciCoin dentro de la aplicación." },
    ],
  },
  las_tunas: {
    metaDescription: "Pide transporte en Las Tunas con TriciGo: triciclo, moto, auto o mensajería en la ciudad, Puerto Padre o Amancio. Precio claro antes de confirmar y seguimiento en vivo.",
    intro: "TriciGo lleva el transporte bajo demanda a Las Tunas, el balcón de Oriente. Desde la ciudad de las esculturas hasta Puerto Padre, en la costa norte, y los bateyes azucareros del sur, pides triciclo, moto, auto o mensajería y conoces el precio antes de confirmar.",
    bodyParagraphs: [
      "La ciudad de Las Tunas, cabecera provincial, es por su trazado llano y sus calles conocidas como la capital de la escultura cubana un terreno cómodo para el triciclo: ideal para moverte por el centro, llegar a la terminal o cargar las compras de la plaza. Cuando necesitas rapidez con poco equipaje, la moto resuelve; para ir en grupo o cubrir distancias hacia los repartos de las afueras, el auto es la mejor opción. Y si lo que quieres es enviar un paquete dentro de la ciudad, la mensajería se encarga. En todos los casos pides desde la app, ves el estimado en CUP y sigues al conductor verificado en tiempo real.",
      "Las Tunas es una provincia mayormente llana, de sabanas y caña, con dos realidades que el transporte bajo demanda atiende bien. Al norte, sobre la costa, Puerto Padre y Manatí miran al mar; Puerto Padre, con su bahía, es el segundo gran núcleo de la provincia. Al sur, Jobabo, Colombia y Amancio crecieron alrededor de la industria azucarera y quedan más distantes de la capital. Entre estos polos median municipios como Jesús Menéndez y Majibacoa, de fuerte tradición cañera. En zonas tan abiertas, pedir un triciclo o una moto desde donde estás evita esperas en paradas fijas.",
      "Para los trayectos largos —de Amancio o Colombia hacia la ciudad de Las Tunas, o de Manatí a Puerto Padre por la franja norte— el auto cubre kilómetros que el triciclo no alcanza con comodidad, mientras la moto agiliza los recorridos cortos dentro de cada poblado. TriciGo prioriza viajes claros y seguros: ves el precio antes de aceptar, pagas en efectivo o con créditos TriciCoin y cuentas con botón SOS durante el trayecto. La disponibilidad depende de los conductores activos en cada municipio, así que conviene abrir la app y confirmar qué servicios operan en tu zona en ese momento.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo o una moto en la ciudad de Las Tunas?", a: "Abre la app de TriciGo, fija tu punto de recogida y tu destino dentro de la provincia (por ejemplo, en el centro de la ciudad de Las Tunas o hacia Puerto Padre), elige triciclo o moto y confirma. Verás el precio estimado en CUP antes de aceptar y, una vez asignado un conductor verificado, podrás seguir su llegada en tiempo real." },
      { q: "¿Sirve TriciGo para ir de Amancio o Jobabo hasta la ciudad de Las Tunas?", a: "Para distancias entre municipios del sur, como Amancio, Colombia o Jobabo, y la cabecera provincial, el auto es la opción más cómoda, ya que cubre kilómetros que el triciclo no alcanza. La cobertura entre poblados depende de los conductores activos en cada zona; abre la app para ver qué viajes están disponibles en ese momento y su precio antes de confirmar." },
      { q: "¿En qué municipios de Las Tunas está disponible TriciGo?", a: "TriciGo se despliega por zonas dentro de la provincia: la ciudad de Las Tunas, los costeros del norte Puerto Padre y Manatí, y los municipios del sur y la zona cañera como Jesús Menéndez, Majibacoa, Jobabo, Colombia y Amancio. La cobertura crece a medida que se suman conductores en cada área; consulta la disponibilidad actual directamente en la app." },
    ],
  },
  holguin: {
    metaDescription: "Pide transporte en Holguín con TriciGo: triciclo, moto, auto o mensajería en la ciudad de los parques, Gibara, Banes, Moa, Mayarí y más. Mira el precio antes de viajar.",
    intro: "TriciGo lleva el transporte bajo demanda a Holguín, en el nororiente de Cuba: de la ciudad de los parques, al pie de la Loma de la Cruz, a la costa de Gibara y Banes y a la sierra minera de Moa. Pides un triciclo, una moto, un auto o mensajería desde el celular y ves el precio antes de confirmar.",
    bodyParagraphs: [
      "En la ciudad de Holguín, cabecera provincial conocida como la ciudad de los parques, los triciclos cubren a diario los trayectos entre el Parque Calixto García, el Parque Céspedes y los repartos que se extienden hacia la Loma de la Cruz. Con TriciGo eliges desde la app lo que necesitas: un triciclo para moverte por el casco urbano, una moto para ganar tiempo en hora pico o un auto cuando llevas equipaje o vas acompañado hacia Cacocum o el aeropuerto. Ves el estimado antes de confirmar, sigues el recorrido en tiempo real y pagas en efectivo o con créditos TriciCoin, con conductores verificados y botón SOS a mano.",
      "Holguín une un centro de interior con una costa norte de mucho movimiento. Hacia el mar están Gibara, la Villa Blanca de los cangrejos, y Rafael Freyre, junto a la bahía de Bariay donde Colón tocó tierra; más al este, Banes guarda la herencia taína y conecta con la zona de playas del litoral. Tierra adentro, los llanos de Báguanos, Calixto García, Urbano Noris y Cueto mueven el azúcar y la agricultura, mientras Antilla mira a la bahía de Nipe. Pedir un viaje a demanda ayuda donde las guaguas escasean o las distancias entre poblados se hacen largas.",
      "El oriente de la provincia es más abrupto: Mayarí, Frank País, Sagua de Tánamo y la zona de Moa se acercan al macizo Nipe-Sagua-Baracoa y a la industria del níquel, con carreteras serranas donde un auto o una moto resuelven mejor que el triciclo. TriciGo también ofrece mensajería para enviar paquetes o documentos dentro de la ciudad de Holguín y entre puntos cercanos, con el mismo seguimiento y precio claro antes de aceptar. El modelo encaja en una provincia de centro urbano activo y municipios dispersos entre la costa y la montaña. La cobertura crece a medida que TriciGo llega a tu zona: consulta la disponibilidad en la app.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo en la ciudad de Holguín?", a: "Abre la app de TriciGo, marca tu recogida y destino dentro de Holguín (por ejemplo del Parque Calixto García a un reparto cercano), elige triciclo y confirma. Verás el precio estimado antes de aceptar y podrás seguir al conductor en tiempo real hasta que llegue." },
      { q: "¿En qué municipios de Holguín funciona TriciGo?", a: "TriciGo se despliega por zonas e incluye la ciudad de Holguín y municipios como Gibara, Banes, Rafael Freyre, Mayarí, Moa, Antilla, Báguanos, Cacocum, Calixto García, Cueto, Urbano Noris, Frank País y Sagua de Tánamo. La cobertura se amplía a medida que llegamos a cada zona; consulta la disponibilidad actual en la app." },
      { q: "¿Sirve TriciGo para ir de Holguín a la costa o a Moa?", a: "Puedes pedir un auto o una moto para trayectos más largos, como salir hacia Gibara o Banes en la costa norte o hacia la zona de Moa y Mayarí en el oriente. Verás el estimado del viaje antes de confirmar, según la disponibilidad de conductores en cada zona." },
    ],
  },
  granma: {
    metaDescription: "Pide triciclo, moto, auto o mensajería en Granma con TriciGo. Transporte bajo demanda en Bayamo, Manzanillo y más, con precio claro y pago en CUP.",
    intro: "TriciGo acerca el transporte bajo demanda a Granma: pide un triciclo, una moto, un auto o un servicio de mensajería desde Bayamo, Manzanillo y otros municipios, con el precio a la vista antes de confirmar.",
    bodyParagraphs: [
      "En Granma, TriciGo conecta la vida diaria de su cabecera, Bayamo, con municipios como Jiguaní, Yara y Guisa. Pides desde la app un triciclo para los trayectos cortos por el centro y los barrios, una moto cuando buscas rapidez, o un auto para distancias más largas o cuando viajas con equipaje. También está la mensajería para enviar y recibir paquetes. Ves el estimado en CUP antes de confirmar, sigues el viaje en tiempo real y pagas en efectivo o con créditos TriciCoin, con botón SOS y conductores verificados.",
      "La geografía de Granma combina el llano del valle del Cauto al norte —en municipios como Río Cauto y Cauto Cristo— con la costa del Golfo de Guacanayabo al oeste, donde Manzanillo, Campechuela, Media Luna y Niquero marcan el ritmo portuario y pesquero. Hacia el sur se levanta la Sierra Maestra, en Bartolomé Masó, Buey Arriba y Pilón. En este territorio diverso, el triciclo resuelve lo cotidiano en cada pueblo, mientras la moto y el auto cubren los trayectos entre municipios cuando hace falta.",
      "El transporte bajo demanda encaja bien en Granma porque combina los desplazamientos urbanos de Bayamo y Manzanillo con la necesidad de moverse entre poblaciones más dispersas. Con TriciGo no dependes de esperar en la parada: pides el vehículo que necesitas, confirmas un precio claro y vas siguiendo la ruta desde el teléfono. A medida que TriciGo llega a más zonas de la provincia, sumamos conductores locales que conocen las calles de cada municipio, desde el casco de Jiguaní hasta el litoral de Niquero.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo en Granma?", a: "Abre la app de TriciGo, indica tu punto de recogida y tu destino dentro de Granma, por ejemplo en Bayamo o Manzanillo, y elige triciclo. Verás el precio estimado en CUP antes de confirmar; luego sigues al conductor en tiempo real hasta que llegue. La disponibilidad depende de tu zona, así que consúltala directamente en la app." },
      { q: "¿En qué municipios de Granma está TriciGo?", a: "TriciGo se despliega por zonas dentro de Granma, empezando por las áreas de mayor movimiento como Bayamo y Manzanillo y ampliándose hacia municipios como Jiguaní, Yara, Niquero o Guisa. La forma más segura de saber si ya operamos en tu municipio es abrir la app y consultar la disponibilidad en tu ubicación." },
      { q: "¿Cómo pago mi viaje en Granma?", a: "Puedes pagar en efectivo en CUP o con créditos TriciCoin desde tu billetera en la app. En ambos casos ves el estimado antes de confirmar, así sabes cuánto costará el trayecto. Para mensajería, moto o auto el precio también se muestra por adelantado según el tipo de servicio y la distancia." },
    ],
  },
  santiago_de_cuba: {
    metaDescription: "Pide triciclo, moto, auto o mensajería en Santiago de Cuba con TriciGo. Transporte bajo demanda, precio claro antes de confirmar y conductores verificados.",
    intro: "TriciGo acerca el transporte bajo demanda a Santiago de Cuba: desde la ciudad cabecera hasta Palma Soriano, Contramaestre o San Luis, pides tu viaje y ves el precio antes de confirmar.",
    bodyParagraphs: [
      "En Santiago de Cuba, la segunda ciudad del país y cabecera provincial, TriciGo te permite pedir un triciclo para trayectos cortos por el casco histórico, una moto para moverte rápido entre barrios, un auto para distancias más largas o un servicio de mensajería para enviar paquetes. El relieve montañoso del entorno, marcado por la Sierra Maestra y las cuestas que rodean la bahía, hace que un transporte ágil y a pedido sea especialmente útil. Abres la app, indicas tu origen y destino, y conoces el precio estimado antes de confirmar el viaje.",
      "La provincia abarca municipios con realidades muy distintas: desde los valles y llanos de Palma Soriano y Contramaestre, hasta Songo-La Maya, San Luis y Mella, además de las zonas serranas de Segundo Frente, Tercer Frente y Guamá, este último abierto al mar Caribe. TriciGo se despliega por zonas, así que la disponibilidad de triciclo, moto o auto puede variar según el municipio y el momento. A medida que TriciGo llega a tu área, podrás consultar en la app qué servicios están activos cerca de ti y solicitar el que mejor se ajuste a tu trayecto.",
      "El transporte bajo demanda encaja bien en la movilidad santiaguera, donde el triciclo es habitual para recorridos urbanos y la moto resuelve los desplazamientos en pendiente con rapidez. Con TriciGo sigues el viaje en tiempo real, pagas en efectivo o con créditos TriciCoin y cuentas con un botón SOS y conductores verificados para mayor tranquilidad. Tanto si te mueves por el centro de Santiago de Cuba como si necesitas enviar algo hacia Palma Soriano o San Luis, la app reúne las opciones de movilidad en un mismo lugar, con tarifas transparentes desde el inicio.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo en Santiago de Cuba?", a: "Abre la app de TriciGo, escribe tu punto de recogida y tu destino dentro de Santiago de Cuba y elige la opción de triciclo. Verás el precio estimado antes de confirmar y, una vez aceptado el viaje, podrás seguir al conductor en tiempo real. La disponibilidad depende de tu zona, así que consulta en la app qué servicios están activos cerca de ti." },
      { q: "¿En qué municipios de Santiago de Cuba está TriciGo?", a: "TriciGo se despliega por zonas dentro de la provincia, que incluye municipios como Santiago de Cuba, Palma Soriano, Contramaestre, San Luis, Songo-La Maya, Mella, Segundo Frente, Tercer Frente y Guamá. La cobertura crece a medida que TriciGo llega a cada área, por lo que la mejor forma de saber si ya operamos en tu municipio es consultar la disponibilidad directamente en la app." },
      { q: "¿Cuánto cuesta un viaje en Santiago de Cuba?", a: "El precio depende de la distancia, el tipo de vehículo (triciclo, moto o auto) y las condiciones del momento. Con TriciGo siempre ves el costo estimado en pesos cubanos (CUP) antes de confirmar, sin sorpresas al final. Puedes pagar en efectivo o con créditos TriciCoin, según lo que prefieras para cada trayecto." },
    ],
  },
  guantanamo: {
    metaDescription: "Pide triciclo, moto, auto o mensajería en Guantánamo con TriciGo. Transporte bajo demanda en la ciudad, Baracoa, Caimanera, Maisí e Imías, con precio claro en CUP.",
    intro: "TriciGo lleva el transporte bajo demanda al extremo oriental de Cuba: la provincia de Guantánamo. Desde la ciudad cabecera hasta Baracoa y Maisí, pides un triciclo, una moto, un auto o un servicio de mensajería y conoces el precio antes de confirmar.",
    bodyParagraphs: [
      "En la ciudad de Guantánamo, asentada en el valle del río Guaso, TriciGo te conecta con un triciclo para los trayectos cortos por el casco urbano, una moto para moverte rápido o un auto cuando llevas equipaje o viajas acompañado. También hay mensajería para enviar paquetes y documentos dentro de la ciudad. Caimanera, junto a la bahía de Guantánamo, queda a corta distancia de la cabecera y forma parte natural de esos desplazamientos. Ves el estimado antes de confirmar, sigues el viaje en tiempo real y pagas en efectivo o con créditos TriciCoin.",
      "Guantánamo es la provincia más oriental del país y su geografía manda: el valle costero del sur por San Antonio del Sur e Imías, las montañas de Yateras y la cuenca del río Toa hacia el nordeste, y Maisí marcando la punta extrema de Cuba. Baracoa, la primera villa fundada en la isla, está separada de la cabecera por la cordillera, con el Yunque y carreteras de montaña como La Farola. En municipios como El Salvador, Manuel Tames o Niceto Pérez, donde las distancias y los caminos varían mucho, pedir el vehículo que se ajusta a cada trayecto resulta práctico.",
      "Pedir un viaje es sencillo: abres la app, marcas origen y destino, eliges triciclo, moto o auto, y confirmas con el precio a la vista en CUP. Cada conductor está verificado y cuentas con un botón SOS durante todo el recorrido. En una provincia donde Baracoa, Maisí o las zonas montañosas de Yateras quedan lejos de la ciudad cabecera, contar con transporte que llega cuando lo necesitas facilita tanto los desplazamientos diarios como los envíos de mensajería dentro de una misma localidad. La cobertura se amplía por zonas, así que consulta la disponibilidad en la app a medida que TriciGo llega a tu barrio.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo en la ciudad de Guantánamo?", a: "Abre la app de TriciGo, indica tu punto de recogida y tu destino dentro de la ciudad de Guantánamo, selecciona el triciclo y confirma. Verás el precio estimado en CUP antes de aceptar y podrás seguir al conductor en tiempo real hasta que llegue." },
      { q: "¿En qué municipios de Guantánamo está disponible TriciGo?", a: "TriciGo se despliega por zonas dentro de la provincia, comenzando por las áreas de mayor demanda como la ciudad de Guantánamo y Caimanera. La cobertura avanza progresivamente hacia municipios como Baracoa, San Antonio del Sur, Imías, Yateras o El Salvador. Consulta la disponibilidad real de tu zona directamente en la app." },
      { q: "¿Sirve TriciGo para llegar a Baracoa o Maisí?", a: "Baracoa y Maisí están separados de la cabecera por la cordillera y carreteras de montaña como La Farola, así que las distancias son largas. TriciGo funciona por zonas: puedes usarlo para tus trayectos dentro de cada localidad donde haya servicio, y siempre ves el estimado en CUP antes de confirmar. Revisa en la app la cobertura disponible en cada municipio." },
    ],
  },
  isla_de_la_juventud: {
    metaDescription: "Pide triciclo, moto, auto o mensajeria en Isla de la Juventud con TriciGo. Transporte bajo demanda en Nueva Gerona y Santa Fe, precio claro en CUP o TriciCoin.",
    intro: "TriciGo acerca el transporte bajo demanda a Isla de la Juventud, el municipio especial situado al sur de la isla principal de Cuba: desde Nueva Gerona, a orillas del río Las Casas, pides un triciclo, una moto o un auto y conoces el precio antes de confirmar.",
    bodyParagraphs: [
      "Isla de la Juventud no es una provincia más: es un municipio especial separado de la Cuba continental por el golfo de Batabanó, al que se llega en catamarán desde el Surgidero de Batabanó o en vuelo hasta el aeropuerto Rafael Cabrera de Nueva Gerona. Ese aislamiento hace que la movilidad interna gane peso propio. Con TriciGo pides un triciclo para el casco urbano de Nueva Gerona, una moto cuando buscas rapidez o un auto para grupos y rutas más largas hacia Santa Fe o La Demajagua. También ofrecemos mensajería dentro de la cabecera. Ves el estimado en CUP antes de confirmar, sigues el viaje en tiempo real y pagas en efectivo o con TriciCoin.",
      "Nueva Gerona, la cabecera, se extiende entre el río Las Casas y las elevaciones de mármol de las sierras de Caballos y de las Casas, que enmarcan la ciudad. Aquí se concentra la vida cotidiana: el centro, el embarcadero y las salidas hacia Santa Fe, segundo núcleo del municipio, y hacia La Fe y La Demajagua. En un territorio mayormente llano y de población dispersa, el transporte bajo demanda resuelve bien el último tramo cuando el servicio regular no alcanza. Con TriciGo eliges el vehículo según el viaje, conoces el precio de antemano y cuentas con conductores verificados y botón SOS en cada trayecto.",
      "Como municipio único, la Isla combina la trama urbana de Nueva Gerona con asentamientos rurales y la franja sur menos poblada, donde un triciclo o una moto suelen ser la opción más práctica para distancias intermedias. TriciGo te da una forma sencilla de pedir ese viaje sin negociar en la calle: abres la app, marcas origen y destino, recibes el estimado y confirmas. El despliegue es por etapas, así que la mejor manera de saber si ya operamos en tu barrio o asentamiento es revisar la disponibilidad directamente en la aplicación, que se actualiza a medida que TriciGo llega a tu zona.",
    ],
    faqs: [
      { q: "¿Cómo pido un triciclo en Nueva Gerona o el resto de la Isla?", a: "Abre la app de TriciGo, escribe tu punto de recogida y tu destino dentro del municipio especial, elige triciclo y verás el precio estimado en CUP antes de confirmar. Al aceptar, te asignamos un conductor verificado y puedes seguir el viaje en tiempo real. El servicio se activa por zonas, comenzando por las de mayor demanda en torno a Nueva Gerona, así que la app te mostrará si el triciclo está disponible cerca de ti en ese momento." },
      { q: "¿En qué zonas de Isla de la Juventud está TriciGo?", a: "Isla de la Juventud es un municipio especial único, sin subdivisiones: Nueva Gerona es la cabecera y existen núcleos como Santa Fe, La Fe y La Demajagua. TriciGo se despliega de forma gradual, empezando por el entorno de Nueva Gerona. Para saber con certeza si ya cubrimos tu barrio o asentamiento, consulta la disponibilidad en la app, que se actualiza a medida que TriciGo llega a tu zona." },
      { q: "¿Cuánto cuesta un viaje en la Isla?", a: "El precio depende de la distancia, el tipo de vehículo que elijas (triciclo, moto o auto) y la ruta. Con TriciGo siempre ves el estimado en CUP antes de confirmar, sin sorpresas ni regateo. Puedes pagar en efectivo o con créditos TriciCoin desde la app. El estimado se calcula al momento, así que basta con introducir tu origen y destino, por ejemplo de Nueva Gerona a Santa Fe, para conocer el costo antes de pedir." },
    ],
  },
};
